trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
variables:
  vmImage: 'ubuntu-latest'
  aksResourceGroup: 'aks-demo'
  acrResourceGroup: ''
  kvResourceGroup: ''
  location: 'UK South'
  subscription: 'Visual Studio Enterprise - MPN'
  serviceConnection: 'infra-demo'

stages:
- stage: DeployKVARM
  displayName: 'Create AKS Cluster'
  jobs:
  - job: RGDeployment
    displayName: Create Resource Group
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    pool:
      vmImage: $(vmImage)
    steps:
    - task: AzureCLI@2
      displayName: Run Azure CLI
      inputs:
      azureSubscription: $(subscription)
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        az group create -l $(location) -n $(aksResourceGroup)


  - job: ARMDeployment
    dependsOn: RGDeployment
    displayName: Deploy ARM Template
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    pool:
      vmImage: $(vmImage)
    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: 'Azure Deployment AKS Cluster: Create or Update'
      inputs:
        azureSubscription: $(serviceConnection)
        subscriptionName: $(subscription)
        resourceGroupName: $(aksResourceGroup:)
        location: $(location)
        cmsfile: 'aks_template/akseploy.json'
        csmParametersFile: 'aks_template/aksdeploy.parameters.json'