trigger:
  branches:
    include:
      - master
      - feature/*
  paths:
    exclude:
      - README.md
variables:
  vmImage: 'ubuntu-latest'
  winImage: 'windows-latest'
  aksResourceGroup: 'aks-demo'
  acrResourceGroup: 'acr-demo'
  kvResourceGroup: 'kv-demo'
  location: 'UK South'
  subscription: 'Visual Studio Enterprise - MPN'
  subscriptionId: '42fd229c-db07-42d3-be34-bc5c98826bc2'
  serviceConnection: 'infra-demo'

stages:
  - stage: LZBlueprint
    displayName: "Create or Update LZ Blueprint"
    jobs:
      - job: BlueprintScript
        pool:
          vmImage: $(vmImage)
        steps:
          - task: AzurePowerShell@4
            displayName: Run LZ Blueprint Task
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: 'filePath'
              scriptPath: './scripts/blueprint.ps1'
              azurePowerShellVersion: latestVersion