trigger:
  branches:
    include:
      - master
      - feature/*
  paths:
    exclude:
      - README.md
variables:
  vmImage: 'ubuntu-latest'
  winImage: 'windows-latest'
  aksResourceGroup: 'aks-demo'
  acrResourceGroup: 'acr-demo'
  kvResourceGroup: 'kv-demo'
  location: 'UK South'
  subscription: 'Visual Studio Enterprise - MPN'
  subscriptionId: '42fd229c-db07-42d3-be34-bc5c98826bc2'
  serviceConnection: 'infra-demo'

stages:
  - stage: RunMgmtGroup
    displayName: "Create Management Groups"
    jobs:
      - job: RunPowerShellScript
        pool:
          vmImage: $(winImage)
        steps:
          - task: AzurePowerShell@4
            displayName: Run PowerShell Task Create Mgmt
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: 'filePath'
              scriptPath: '$(Build.SourcesDirectory)\mgmtGroup\mgmtGroup.ps1'
              azurePowerShellVersion: latestVersion