trigger:
  branches:
    include:
      - master
      - feature/*
  paths:
    exclude:
      - README.md
variables:
  vmImage: 'ubuntu-latest'
  serviceConnection: 'infra-demo'

stages:
  - stage: ManagementGroup
    displayName: "Create or Update Management Group Task"
    jobs:
      - job: ManagementGroupScript
        pool:
          vmImage: $(vmImage)
        steps:
          - task: AzurePowerShell@4
            displayName: Run Management Group Task
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: 'filePath'
              scriptPath: './scripts/mgmtGroup.ps1'
              azurePowerShellVersion: latestVersion


  - stage: LZBlueprint
    displayName: "Create or Update LZ Blueprint"
    jobs:
      - job: BlueprintScript
        pool:
          vmImage: $(vmImage)
        variables:
          blueprintName: "LandingZone"
          mgmtGroupName: "Management"
          version: $(BuildID)
          KVAccessPolicy: $(KVAccessPolicy)
          SubId: $(SubId)
          bluePrintRG: "azure-devops"
          UserIdentity: "/subscriptions/$(SubId)/resourceGroups/$(bluePrintRG)/providers/Microsoft.ManagedIdentity/userAssignedIdentities/blueprint"
        steps:
          - task: AzurePowerShell@4
            displayName: Run LZ Blueprint Task
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: 'filePath'
              scriptPath: './scripts/blueprint.ps1'
              scriptArguments:
                -BlueprintName $(blueprintName) `
                -mgmtGroupName $(mgmtGroupName) `
                -KVAccessPolicy $(KVAccessPolicy) `
                -SubId $(SubId) `
                -UserIdentity $(UserIdentity)
              azurePowerShellVersion: latestVersion