trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
variables:
  vmImage: 'ubuntu-latest'
  aksResourceGroup: ''
  acrResourceGroup: ''
  kvResourceGrup: ''
  location: 'UK South'
  subscription: 'Visual Studio Enterprise - MPN'
  serviceConnection: 'infra-demo'

stages:
- stage: DeployKVARM
  displayName: 'Create KeyVault'
  jobs:
  - job: ARMDeployment
    displayName: Deploy ARM Template
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    pool:
      vmImage: $(vmImage)
    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: 'Azure Deployment KeyVault: Create or Update'
      inputs:
        azureSubscription: $(serviceConnection)
        subscriptionName: $(subscription)
        resourceGroupName: $(kvResourceGrup)
        location: $(location)
        cmsfile: 'aks_template/azuredeploy.json'
        csmParametersFile: 'keyvault_template/azuredeploy.parameters.json'